title: Young Pirates of Europe

remote_theme: daattali/beautiful-jekyll@6.0.1

title-img: "icon.svg"

include: 
  - _includes
site-css:
  - "/_includes/styling.css"

remove-ads: true

social-network-links:
  email: office@young-pirates.eu
  rss: false
  facebook: youngpiratesEU
  twitter: YoungPiratesEU
  github: Fhavlonir/YPE-placeholder

defaults:
  -
    scope:
      path: ""
    values:
      footer-extra: info.html
      cover-img: "/construction.md"
